export const cartResponse = {
  success: true,
  message: 'Información procesada de forma correcta.',
  data: {
    code: '38e23e10-3b56-4a39-90a4-e990356a7d11',
    status: 'PENDIENTE',
    payment_method: '',
    quantity: 35,
    subtotal: 42044.4915,
    total_taxes: 7568.0085,
    total_shipments: 7837.56,
    discounts: 0,
    total: 57450.06,
    items: [
      {
        id: 10,
        quantity: 3,
        subtotal: 1875,
        total_taxes: 337.5,
        discounts: 0,
        total: 2212.5,
        data: {
          item_id: 2227,
          quantity: 3,
        },
        item: {
          id: 2227,
          brand: {
            id: 4,
            marca: 'ZENZI',
          },
          files: [],
          price: 625,
          stock: 500,
          prices: [],
          weight: 50,
          barcode: '1000000025555555',
          currency: {
            id: 'PEN',
            symbol: 'S/',
            description: 'Soles',
          },
          in_offer: false,
          variants: [],
          min_order: 0,
          unit_type: {
            id: 'MTR',
            description: 'Metros',
          },
          additional: null,
          description: 'Producto # 4',
          internal_id: 'PAN004',
          offer_price: 0,
          has_variants: false,
          specifications: [],
        },
      },
      {
        id: 11,
        quantity: 30,
        subtotal: 38135.5932,
        total_taxes: 6864.4068,
        discounts: 0,
        total: 45000,
        data: {
          item_id: 380,
          quantity: 30,
        },
        item: {
          id: 380,
          brand: {
            id: 5,
            marca: 'PASSION',
          },
          files: [],
          price: 1500,
          stock: 0,
          prices: [],
          weight: 65,
          barcode: null,
          currency: {
            id: 'PEN',
            symbol: 'S/',
            description: 'Soles',
          },
          in_offer: false,
          variants: [],
          min_order: 0,
          unit_type: {
            id: 'NIU',
            description: 'Unidades',
          },
          additional: null,
          description: 'COLCHON POCKET 1023R KING ZISE',
          internal_id: 'COL-POC004',
          offer_price: 0,
          has_variants: false,
          specifications: [],
        },
      },
      {
        id: 12,
        quantity: 2,
        subtotal: 2033.8983,
        total_taxes: 366.1017,
        discounts: 0,
        total: 2400,
        data: {
          item_id: 383,
          quantity: 2,
        },
        item: {
          id: 383,
          brand: {
            id: 5,
            marca: 'PASSION',
          },
          files: [],
          price: 1200,
          stock: 0,
          prices: [],
          weight: 55,
          barcode: null,
          currency: {
            id: 'PEN',
            symbol: 'S/',
            description: 'Soles',
          },
          in_offer: false,
          variants: [],
          min_order: 0,
          unit_type: {
            id: 'NIU',
            description: 'Unidades',
          },
          additional: null,
          description: 'COLCHON POCKET 744R QUEEN ZISE',
          internal_id: 'COL-POC003',
          offer_price: 0,
          has_variants: false,
          specifications: [],
        },
      },
    ],
    shipment: {
      type: 'DOMICILIO',
      details: {
        price: 6642,
        lead_time: 1,
      },
      weight: '2210.0000',
      subtotal: '6642.0000',
      total: 7837.56,
      address: 'Calle las dlores s/n',
      extra: [
        {
          Ubigeo: '10',
          Departamento: 'Lima',
        },
        {
          Ubigeo: '1010',
          Provincia: 'Lima',
        },
        {
          Ubigeo: '101001',
          Distrito: 'Lima',
        },
      ],
      postal_code: '101155',
      arrives_from: '2023-11-21 12:01:10',
      arrives_to: '2023-11-21 14:01:10',
      receives_name: 'Alice Cerna Mendonza',
      requirements: 'Agregame mi boleta al correo joel201087@gmail.com',
    },
  },
};
